### ISSUE TITLE
Compare with Meteor redpubsub

### ISSUE THREAD

**Issue by fabiodr** [wojtkowiak/meteor-direct-stream-access#1]
Hi, can you tell how this compare, mainly about performance and multiple servers scalability, with this project: [https://github.com/chatr/redpubsub](url) ?

Thanks!

**Comment by wojtkowiak** [comment]
Hey, this redpubsub seems like a really great solution, never heard about it earlier. Hard to compare it in any way, from what I've read it is a solution which essence is to replace the oplog tailing mechanism with a custom solution that notifies each meteor instance about a write/change to collection. 

My packages basically are just allowing you to send anything to your clients through the default meteor socket connection. So improving your app data distribution performance is still up to you, but at least you have a channel for data distribution available.

You can for example do something like described here: https://medium.com/@omriklinger/how-to-send-1000-updates-sec-per-client-using-meteor-and-stay-alive-88eba7588c36#.c29vki77f 
To disable merge box you can use https://github.com/peerlibrary/meteor-control-mergebox and for sending data my package will be helpful.
What I am also doing is just listening with `observeChanges` on the server and distributing the data with my own protocol.

Anyway, back to your question - the only thing to compare is the actual data sending mechanism, and in case redpubsub they are using plain DDP which is actually what they need since they want the data to be pulled into minimongos collections automatically. With this package you can build a DDP message yourself if you want and get the same effect but it will require some work. What I am using now is a collection insert (on the client) if I want the data to be in minimongo. On the custom-protocol package roadmap I have the support for sending plain DDP messages, so that you will be able to feed you clients minimongos with one step less.

**Comment by fabiodr** [comment]
Thanks for the explanation! I was wandering if there is some deserialization in browser faster than JSON parse, to send big size data with this. Maybe avro, flatbuffer, bson... i did some benchmarks deserializing bson in browser and its not bad. The MongoDB BSON to JSON parse of large datasets can take too much time in server, especially with older drivers, wich Meteor is still using.
