### ISSUE TITLE
Can not send binary data

### ISSUE THREAD

**Issue by dr-dimitru** [wojtkowiak/meteor-direct-stream-access#3]
Trying to send `Blob`, `File` or `FormData`, failed message is just stringifyied to:

`[object Blob]`, `[object File]` and `[object FormData]`

I need to send any of those types, not all of them. Could you please provide a quick example for binary data sending?

**Comment by dr-dimitru** [comment]
@wojtkowiak any one is alive here?

**Comment by wojtkowiak** [comment]
Hey,
sorry, just got back yesterday from two week holidays.

Well sending binary data is a tough one because Meteor uses SockJS which at the version used in Meteor only supports strings. So you have take care of stringifying your data properly and when it comes to binary data it is rather complicated.

Without googling, the first way I would go is try to convert those to `ArrayBuffer` and then to `String`. You need to check if that is even doable and worthy to do. `Blob` should be easy, `File` is also a `Blob` I guess. Not sure about `FormData` you will have to check it.

Here you have an example of how I encoded some binary data from `ArrayBuffers` into a string https://github.com/wojtkowiak/meteor-transfer-rate-monitor/blob/master/src/lib/TransferRate.protocol.js
It is less than perfect, but works.

What you are trying to do is possible but complicated, therefore if that is possible for you I would rather recommend opening a separate communication channel like REST endpoint or another websocket connection to push binary data.

I hope that helps, if not let me know.

**Comment by dr-dimitru** [comment]
Thank you for reply.
Not a my case, need binary transfer without modifications, see: https://github.com/VeliovGroup/Meteor-Files/issues/176

I guess I'll just use pure WebSockets, which supports binary data out of the box.
From your experience is there any disadvantages in having two parallel WebSocket connection?
But I'll open it only for file upload then close.

**Comment by wojtkowiak** [comment]
Well I would actually try to check the performance of converting `Blob` to `ArrayBuffer` with `FileReader` and then to utf-8 string with `TextDecoder`. Then you could probably avoid byte-by-byte loops.

If your are not in a hurry I can check this next week and if it is feasible I will add this feature to custom-protocols or direct-stream.

When it comes to opening another websocket connection at first glance I do not see any disadvantages. The question is can we omit making connection with libs like sockjs or socket.io. If no then a con would be the size of the lib.

**Comment by wojtkowiak** [comment]
Can I close this issue?

**Comment by dr-dimitru** [comment]
Yes.

In case someone looking for binary uploads:
- Binary isn't actually supported, you can upload TypedArrays (like ArrayBuffer in uint8 view)
- Converting to/from TypedArrays on client/server took more time, than sending as base64 string

Hope it helps to other folks, I've spent a week on this.
Btw played with RTC Data Channels for upload to server, binary (again as ArrayBuffer) works like a charm, twice faster than WebSockets. But overwhelming in chunking, as chunk may not be larger than 64,000 bytes

**Comment by wojtkowiak** [comment]
Just curious, how did you actually established RTC data channel from client to server? I mean did you use some kind of npm package on the server that implements it?

**Comment by dr-dimitru** [comment]
yes, `wrtc@0.0.61`
It's tricky, but I can send you a link to package once it will be published.
I integrated it into [Meteor-Files](https://github.com/VeliovGroup/Meteor-Files), as additional transport, along with `DDP` and `HTTP`
